import { expect, test } from "@playwright/test";
import nextConfig from "./next.config";

async function configuredHeaders() {
  if (typeof nextConfig.headers !== "function") {
    throw new Error("next.config.ts must define response headers");
  }

  return nextConfig.headers();
}

test.describe("response security and private caching", () => {
  test("publishes the immutable web revision on every response", async () => {
    const rules = await configuredHeaders();
    const global = rules.find((rule) => rule.source === "/:path*");

    expect(global?.headers).toContainEqual({
      key: "X-App-Revision",
      value: expect.stringMatching(/^(?:unknown|[a-f0-9]{40})$/u),
    });
  });

  test("does not publish a static unsafe-inline script policy", async () => {
    const rules = await configuredHeaders();
    const configuredPolicies = rules
      .filter((rule) => rule.source !== "/offline.html")
      .flatMap((rule) =>
        rule.headers.filter(
          (header) => header.key.toLowerCase() === "content-security-policy",
        ),
      );

    // The request-scoped nonce policy is generated by proxy.ts. A static CSP
    // here would be combined by browsers and could silently re-open scripts.
    expect(configuredPolicies).toEqual([]);
  });

  test("blocks every script in the static offline fallback", async () => {
    const rules = await configuredHeaders();
    const offline = rules.find((rule) => rule.source === "/offline.html");
    const policy = offline?.headers.find(
      (header) => header.key.toLowerCase() === "content-security-policy",
    )?.value;

    expect(policy).toContain("script-src 'none'");
    expect(policy).toContain("script-src-attr 'none'");
    expect(policy).toContain("form-action 'none'");
  });

  test("keeps every authenticated dashboard response out of shared caches", async () => {
    const rules = await configuredHeaders();
    const dashboard = rules.find(
      (rule) => rule.source === "/dashboard/:path*",
    );

    expect(dashboard).toBeDefined();
    expect(dashboard?.headers).toEqual(
      expect.arrayContaining([
        {
          key: "Cache-Control",
          value: "private, no-store, no-cache, max-age=0, must-revalidate",
        },
        { key: "Pragma", value: "no-cache" },
        { key: "X-Robots-Tag", value: "noindex, nofollow, noarchive" },
      ]),
    );
  });

  test("does not cache invitation URLs that can carry a one-time token", async () => {
    const rules = await configuredHeaders();
    const invitation = rules.find(
      (rule) => rule.source === "/aceptar-invitacion",
    );

    expect(invitation?.headers).toContainEqual({
      key: "Cache-Control",
      value: "private, no-store, no-cache, max-age=0, must-revalidate",
    });
  });
});
