import { isOwnedCanonicalStoragePath } from './tenant-storage-path.util';

const CANONICAL_PATH = 'tenant-a/e14/123e4567-e89b-42d3-a456-426614174000.pdf';

describe('isOwnedCanonicalStoragePath', () => {
  const options = {
    tenantId: 'tenant-a',
    module: 'e14',
    allowedExtensions: ['jpg', 'jpeg', 'png', 'webp', 'pdf'],
  } as const;

  it('accepts the tenant/module/UUID.ext format generated by StorageService', () => {
    expect(
      isOwnedCanonicalStoragePath({ ...options, path: CANONICAL_PATH }),
    ).toBe(true);
  });

  it.each([
    'tenant-b/e14/123e4567-e89b-42d3-a456-426614174000.pdf',
    'tenant-a/finance/123e4567-e89b-42d3-a456-426614174000.pdf',
  ])('rejects a path outside the authorized tenant or module: %s', (path) => {
    expect(isOwnedCanonicalStoragePath({ ...options, path })).toBe(false);
  });

  it.each([
    'tenant-a/e14/not-a-uuid.pdf',
    'tenant-a/e14/123e4567-e89b-12d3-a456-426614174000.pdf',
    'tenant-a/e14/123e4567-e89b-42d3-a456-426614174000-acta.pdf',
  ])('rejects a non-canonical UUID object name: %s', (path) => {
    expect(isOwnedCanonicalStoragePath({ ...options, path })).toBe(false);
  });

  it.each([
    'tenant-a/e14/../123e4567-e89b-42d3-a456-426614174000.pdf',
    'tenant-a/e14/%2e%2e/123e4567-e89b-42d3-a456-426614174000.pdf',
    'tenant-a/e14\\123e4567-e89b-42d3-a456-426614174000.pdf',
    'tenant-a/e14/nested/123e4567-e89b-42d3-a456-426614174000.pdf',
  ])('rejects traversal or nested paths: %s', (path) => {
    expect(isOwnedCanonicalStoragePath({ ...options, path })).toBe(false);
  });

  it('rejects an extension outside the module allowlist', () => {
    expect(
      isOwnedCanonicalStoragePath({
        ...options,
        path: 'tenant-a/e14/123e4567-e89b-42d3-a456-426614174000.exe',
      }),
    ).toBe(false);
  });
});
