-- Seed the system-wide plan catalog as deploy-time data. This keeps API
-- startup read-only while making a fresh database immediately usable.
INSERT INTO "SubscriptionPlan" (
  "id",
  "name",
  "code",
  "description",
  "maxUsers",
  "maxVoters",
  "maxStorageMb",
  "includesExport",
  "includesImport",
  "includesMfa",
  "includesApi",
  "monthlyPriceCop",
  "yearlyPriceCop",
  "isActive",
  "sortOrder",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    'seed-subscription-plan-free-v1',
    'Piloto',
    'FREE',
    'Ediles, Concejos municipios 6ta cat.',
    3,
    500,
    50,
    false,
    false,
    false,
    false,
    0,
    0,
    true,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'seed-subscription-plan-starter-v1',
    'Starter',
    'STARTER',
    'Concejales capitales, Alcaldías cat. 4-6',
    15,
    5000,
    500,
    true,
    false,
    false,
    false,
    290000,
    3480000,
    true,
    2,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'seed-subscription-plan-professional-v1',
    'Profesional',
    'PROFESSIONAL',
    'Alcaldías cat. 3-Especial, Asambleas, Cámara',
    50,
    50000,
    2048,
    true,
    true,
    true,
    false,
    990000,
    11880000,
    true,
    3,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'seed-subscription-plan-enterprise-v1',
    'Enterprise',
    'ENTERPRISE',
    'Gobernaciones, grandes capitales, Senado',
    999999,
    999999,
    999999,
    true,
    true,
    true,
    false,
    3500000,
    42000000,
    true,
    4,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
-- Update existing plans with the official commercial pricing and limits.
ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "maxUsers" = EXCLUDED."maxUsers",
  "maxVoters" = EXCLUDED."maxVoters",
  "maxStorageMb" = EXCLUDED."maxStorageMb",
  "monthlyPriceCop" = EXCLUDED."monthlyPriceCop",
  "yearlyPriceCop" = EXCLUDED."yearlyPriceCop",
  "updatedAt" = CURRENT_TIMESTAMP;
