services:
  migrate:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  catalog-worker:
    extra_hosts:
      - "host.docker.internal:host-gateway"
