import { plainToInstance } from 'class-transformer';
import { validate } from 'class-validator';
import { CuidIdParamsDto } from './cuid-id-params.dto';

describe('CuidIdParamsDto', () => {
  const validCuid = 'ckl0z7u4f0000qzrmn831i7rn';

  it('accepts the canonical format generated by Prisma cuid()', async () => {
    const params = plainToInstance(CuidIdParamsDto, { id: validCuid });

    await expect(validate(params)).resolves.toHaveLength(0);
  });

  it.each([
    '',
    'entry-a',
    'CKL0Z7U4F0000QZRMN831I7RN',
    'ckl0z7u4f0000qzrmn831i7r',
    'ckl0z7u4f0000qzrmn831i7rnn',
    'ckl0z7u4f0000qzrmn831i7r-',
    '../tenant-b',
    ' ckl0z7u4f0000qzrmn831i7rn',
    '7c8f80d8-66c5-4f3a-9745-b66219c13f74',
  ])('rejects non-canonical resource identifier %p', async (id) => {
    const errors = await validate(plainToInstance(CuidIdParamsDto, { id }));

    expect(errors.map(({ property }) => property)).toContain('id');
  });

  it('does not accept a tenant identifier from route parameters', async () => {
    const errors = await validate(
      plainToInstance(CuidIdParamsDto, {
        id: validCuid,
        tenantId: 'tenant-controlled-by-client',
      }),
      { whitelist: true, forbidNonWhitelisted: true },
    );

    expect(errors.map(({ property }) => property)).toContain('tenantId');
  });
});
